language: cpp
cache: ccache
sudo: required
dist: trusty
os:
  - linux
env:
  #- JOB="-p NVIDIA-GPU -o Centos"
  #- JOB="-p NVIDIA-GPU -o Ubuntu"
  - JOB="-p AMD_GPU -o Centos"
  - JOB="-p AMD_GPU -o Ubuntu"
  #- JOB="-p X86-ONLY -o Centos"
  #- JOB="-p X86-ONLY -o Ubuntu"
  #- JOB="-p ARM -o Centos"
  #- JOB="-p ARM -o Ubuntu"

compiler:
  - gcc

services:
  - docker

install:
  - sudo apt-get install nvidia-cuda-toolkit

script:
  - cd docker
  - bash anakin_docker_build_and_run.sh ${JOB} -m Build

branches:
  only:
  - master
  - developing
  - AMD

notifications:
  email:
    recipients:
    - xukailu@baidu.com
    on_success: change
    on_failure: always
